'use client'

import { useState } from 'react'
import { useAppState } from '@/lib/client/app-state'
import { useZgStatus } from '@/lib/client/status-context'
import type { HistoryPointer, SummaryOutput } from '@/lib/types'
import { Mono, Spinner, truncateHash } from '@/components/ui'

type Stage = 'idle' | 'inference' | 'saving' | 'done' | 'error'

interface Result {
  output: SummaryOutput
  rootHash: string
  txHash: string
  provider: string
  model: string
  queried: string
  createdAt: string
}

export function ResearchMain() {
  const { ownerId, addPointer } = useAppState()
  const status = useZgStatus()
  const [raw, setRaw] = useState('')
  const [stage, setStage] = useState<Stage>('idle')
  const [error, setError] = useState<string | null>(null)
  const [result, setResult] = useState<Result | null>(null)

  const busy = stage === 'inference' || stage === 'saving'
  const disabled = status.loading || !status.configured

  async function submit(e: React.FormEvent) {
    e.preventDefault()
    if (!raw.trim()) {
      setError('Paste a link, contract address, thread, or some text first.')
      setStage('error')
      return
    }

    setError(null)
    setResult(null)
    setStage('inference')

    try {
      const res = await fetch('/api/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ raw, owner: ownerId }),
      })
      setStage('saving')
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Summarize failed.')

      const record = data.record
      setResult({
        output: record.output,
        rootHash: data.rootHash,
        txHash: data.txHash,
        provider: record.provider,
        model: record.model,
        queried: raw.trim(),
        createdAt: record.createdAt,
      })
      setStage('done')

      const pointer: HistoryPointer = {
        rootHash: data.rootHash,
        txHash: data.txHash,
        type: 'summary',
        owner: ownerId,
        title: raw.trim().slice(0, 80),
        preview: record.output.bottomLine,
        createdAt: record.createdAt,
      }
      addPointer(pointer)
    } catch (err) {
      setError((err as Error).message)
      setStage('error')
    }
  }

  return (
    <div className="mx-auto max-w-2xl px-6 py-6">
      <form onSubmit={submit}>
        <div className="rounded-xl border border-base-700 bg-base-900 focus-within:border-accent/50">
          <textarea
            value={raw}
            onChange={(e) => setRaw(e.target.value)}
            rows={3}
            placeholder="What do you want to research?"
            className="w-full resize-none bg-transparent px-4 pt-3.5 text-sm text-base-100 placeholder:text-base-500 focus:outline-none"
          />
          <div className="flex items-center justify-between px-4 pb-3">
            <p className="text-[11px] text-base-600">
              Paste a link, contract address, thread, or raw text.
            </p>
            <button
              type="submit"
              disabled={disabled || busy}
              title={disabled ? '0G backend not configured' : undefined}
              className="inline-flex items-center gap-2 rounded-lg bg-accent px-3.5 py-1.5 text-xs font-medium text-base-950 transition-colors hover:bg-accent-dim disabled:cursor-not-allowed disabled:opacity-40"
            >
              {busy && <Spinner className="h-3 w-3" />}
              {stage === 'inference' && 'Running on 0G Compute…'}
              {stage === 'saving' && 'Saving to 0G Storage…'}
              {!busy && 'Research'}
            </button>
          </div>
        </div>
      </form>

      {error && (
        <div className="mt-5 rounded-xl border border-danger/30 bg-danger/5 p-4">
          <p className="text-sm text-danger">{error}</p>
        </div>
      )}

      {!result && !error && !busy && (
        <div className="mt-16 text-center">
          <p className="text-sm text-base-400">No research yet.</p>
          <p className="mx-auto mt-1.5 max-w-sm text-xs leading-relaxed text-base-600">
            Your summary will appear here once you run it. Nothing is pre-loaded — every
            result is generated by 0G Compute and saved to 0G Storage.
          </p>
        </div>
      )}

      {result && (
        <article className="mt-6">
          <header className="flex flex-wrap items-center gap-x-3 gap-y-1">
            <h2 className="flex items-center gap-2 text-base font-semibold text-base-100">
              <span className="text-accent">✦</span> AI summary
            </h2>
            <span className="inline-flex items-center gap-1.5 rounded-full border border-accent/25 bg-accent-soft px-2.5 py-0.5 text-[10px] font-medium text-accent">
              Saved to 0G Storage
            </span>
          </header>
          <p className="mt-1.5 truncate text-[11px] text-base-500">
            Queried: {result.queried} · {new Date(result.createdAt).toLocaleTimeString()}
          </p>

          <div className="mt-5 space-y-3">
            <Section title="Key points" tone="neutral">
              <ul className="space-y-1.5">
                {result.output.keyPoints.map((p, i) => (
                  <li key={i} className="flex gap-2.5 text-sm leading-relaxed text-base-200">
                    <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-accent" />
                    {p}
                  </li>
                ))}
              </ul>
            </Section>

            <Section title="Risks" tone="warn">
              {result.output.risks.length > 0 ? (
                <ul className="space-y-1.5">
                  {result.output.risks.map((r, i) => (
                    <li key={i} className="flex gap-2.5 text-sm leading-relaxed text-base-200">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-warn" />
                      {r}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-sm text-base-500">None flagged.</p>
              )}
            </Section>

            <Section title="Bottom line" tone="accent">
              <p className="text-sm leading-relaxed text-base-100">{result.output.bottomLine}</p>
            </Section>
          </div>

          <footer className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-1 border-t border-base-800 pt-3 text-[11px] text-base-600">
            <span>
              Root hash <Mono className="text-base-400">{truncateHash(result.rootHash, 8)}</Mono>
            </span>
            <span>
              Tx <Mono className="text-base-400">{truncateHash(result.txHash, 8)}</Mono>
            </span>
            <span>
              Model <Mono className="text-base-400">{result.model}</Mono>
            </span>
          </footer>
          <p className="mt-3 text-[11px] text-base-600">
            AI-generated summary may contain errors. Always do your own research.
          </p>
        </article>
      )}
    </div>
  )
}

function Section({
  title,
  tone,
  children,
}: {
  title: string
  tone: 'neutral' | 'warn' | 'accent'
  children: React.ReactNode
}) {
  const ring = {
    neutral: 'border-base-700',
    warn: 'border-warn/25',
    accent: 'border-accent/25',
  }[tone]

  return (
    <section className={`rounded-xl border ${ring} bg-base-900 p-4`}>
      <h3 className="text-xs font-medium uppercase tracking-wide text-base-500">{title}</h3>
      <div className="mt-2.5">{children}</div>
    </section>
  )
}
